Update info.vue
koishijs/webui pull request #141
Opened 2023-04-01 10:15 UTC by idanran

1. "依赖"存在歧义
2. 按钮没有指针

2023-04-01 13:35 UTC, shigma requested changes

2023-04-01 13:35 UTC, shigma commented on packages/market/client/settings/slots/info.vue
> +    <p>尚未将当前插件列入生产依赖，<a @click="send('market/install', { [data.name]: data.local.version })" style='cursor: pointer;'>点击添加</a>。</p>
WebUI 默认生产依赖，用户无法理解什么是开发依赖。

2023-04-01 14:29 UTC, idanran commented on packages/market/client/settings/slots/info.vue
> +    <p>尚未将当前插件列入生产依赖，<a @click="send('market/install', { [data.name]: data.local.version })" style='cursor: pointer;'>点击添加</a>。</p>
hmr 插件的提示具有误导性，或许需要一种方法关闭提示。

2023-04-01 15:20 UTC, shigma commented on packages/market/client/settings/slots/info.vue
> +    <p>尚未将当前插件列入生产依赖，<a @click="send('market/install', { [data.name]: data.local.version })" style='cursor: pointer;'>点击添加</a>。</p>
为什么生产环境就不需要 hmr？

2023-04-01 15:58 UTC, idanran commented on packages/market/client/settings/slots/info.vue
> +    <p>尚未将当前插件列入生产依赖，<a @click="send('market/install', { [data.name]: data.local.version })" style='cursor: pointer;'>点击添加</a>。</p>
> 为什么生产环境就不需要 hmr？

hmr 一般是在开发的情况下使用。

2023-04-01 16:04 UTC, shigma commented on packages/market/client/settings/slots/info.vue
> +    <p>尚未将当前插件列入生产依赖，<a @click="send('market/install', { [data.name]: data.local.version })" style='cursor: pointer;'>点击添加</a>。</p>
你不能预设这件事，哪怕是不安全插件都有人会用，凭什么 market 插件要假定一个插件不能在什么情况下使用？

2023-04-01 16:06 UTC, shigma commented on packages/market/client/settings/slots/info.vue
> +    <p>尚未将当前插件列入依赖，<a @click="send('market/install', { [data.name]: data.local.version })" style='cursor: pointer;'>点击添加</a>。</p>
```suggestion
    <p>尚未将当前插件列入依赖，<span class="link" @click="send('market/install', { [data.name]: data.local.version })">点击添加</span>。</p>
```

2023-04-02 01:52 UTC, idanran commented on packages/market/client/settings/slots/info.vue
> +    <p>尚未将当前插件列入生产依赖，<a @click="send('market/install', { [data.name]: data.local.version })" style='cursor: pointer;'>点击添加</a>。</p>
> 你不能预设这件事，哪怕是不安全插件都有人会用，凭什么 market 插件要假定一个插件不能在什么情况下使用？

有道理

2023-04-02 04:14 UTC, shigma approved these changes

2023-04-02 04:15 UTC, merged